<div id="menu">
    <ul>
        <!INDIETRO>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'index',
                                        ), 
                                        'default',true);?>" title="Torna alla home di area riservata">Indietro	</a></p>
        </li>
        <!Aggiungi Utente>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'newutente',
                                        ), 
                                        'default',true);?>" title="Aggiungi una nuova Utente">Aggiungi Utente	</a></p>
        </li>
        <!Modifica Utente>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'modutente',
                                        ), 
                                        'default',true);?>" title="Modifica una Utente">Modifica Utente	</a></p>
        </li>


    </ul>
</div>