<div id="flayer">	


    <div id="titol">
        <h2> Sconto per: <?= $this->promo["titolo"] ?> </h2>
    </div>
    <p>
        <?= $this->utente["nome"]."<br>".$this->utente["cognome"] ?> hai ottenuto il seguente sconto:
    </p>
    <div id="prezz">

        <p> <?= $this->promo->getPrice($this->promo["sconto"]) ?> </p>
        <p>
            <del>
                <?= $this->promo["prezzo"] ?>
            </del>
            <br><?= $this->promo["sconto"] ?>%            </p>

    </div>

    <div id="descrizione">
        <p>
            <?= $this->promo["descrizione"] ?>
        </p>
    
        <p>
            Potrai ritirare il prodotto al seguente indirizzo:<br>
            <?= $this->azienda["ragione_sociale"] ?><br>
            <?= $this->azienda["indirizzo"] ?><br>
        </p>
        <br>
        <p>
            CODICE COUPON: <?= $this->coupon["ID_Coupon"] ?>
        </p>
        <p>
            Il seguente coupon è stato emesso da:<br>
            <img src=<?= $this->logo ?>>
        </p>
        
        <div id="btn_flayer">
            
        <?= $this->SalvaCoupon() ?>
        </div>
        <div id="btn_flayer" class="due">
        <?= $this->Continua() ?>
            
        </div>

    </div>
</div>    
