<?php
$this->headScript()
        ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
        ->appendFile($this->baseUrl('js/functions.js'))
        ->captureStart()
?>

$(function()
{
    $('div#stampa').on('click', function(event){

        $('div#doppio').hide();
        $('div.btn_flayer').hide();
        
        window.print();    
        
        $('div.btn_flayer').show();
        $('div#doppio').show();
    });

   


});

<?php $this->headScript()->captureEnd() ?>


<div id="flayer">	

    <div id="titol">
        <h2> Sconto per: <?= $this->promo["titolo"] ?> </h2>
    </div>
    <p>
        <?= $this->utente["nome"] . "<br>" . $this->utente["cognome"]. "<br>" ?> hai ottenuto il seguente sconto:
    </p>
    <div id="prezz">

        <p> <?= $this->Price($this->promo) ?> </p>
        
    </div>

    <div id="descrizione">
        <p>
            <?= $this->promo["descrizione"] ?><br>
            <?= $this->categoria["nome"] ?>
        </p>
    </div>
    <p>
        Potrai ritirare il prodotto al seguente indirizzo:<br>
        <?= $this->azienda["ragione_sociale"] ?><br>
        <?= $this->azienda["indirizzo"] ?><br>
    </p>
    <br>
    <p>
        CODICE COUPON: <?= $this->coupon["ID_Coupon"] ?>
    </p>
    <p>
        Il seguente coupon è stato emesso da:<br>
        <img src=<?= $this->logo ?>>
    </p>

    <div class="btn_flayer" id="stampa">
        <input type="submit" value="Stampa" class="ottieni">
    </div>

  
    <div class="btn_flayer" class="due">
        <?= $this->Continua() ?>
    </div>

    <?php if ($this->doppio == "si"): ?>
        <p>
        <br><div id="doppio">Attenzione! Hai già acquisito questo coupon, potrai usufruirne una sola volta!</div>
    </p>
<?php endif; ?>
</div>    