<?php
$this->headScript()
        ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
        ->appendFile($this->baseUrl('js/functions.js'))
        ->captureStart()
?>

$(function()
{
    $('div#stampa').on('click', function(event){
        stampaCoupon();        
    });
});

<?php $this->headScript()->captureEnd() ?>


<div id="flayer">	

    <div id="titol">
        <h2> Sconto per: <?= $this->promo["titolo"] ?> </h2>
    </div>
    <p>
        <?= '<b>Nome: </b>'. $this->utente["nome"] . "<br><b>Cognome: </b>" . $this->utente["cognome"]. "<br>" ?><b> hai ottenuto il seguente sconto:</b>
    </p>
    <div id="prezz">

        <p> <?= $this->Price($this->promo) ?> </p>
        
    </div>

    <div id="descrizione">
        <p>
            <b><?= $this->promo["descrizione"] ?></b><br>
        </p>
    </div>
    <br>
    <p>
        <b>Potrai ritirare il prodotto al seguente indirizzo:</b><br>
        <?= $this->azienda["ragione_sociale"] ?><br>
        <?= $this->azienda["citta"] ?><br>
        <?= $this->azienda["indirizzo"] ?><br>
    </p>
    <br>
     <p>
         <b>Potrai ritirare usufruire della promozione</b><br>
        <?= '<b> dal:</b> '.$this->promo["inizio"].' <b>al:</b> '. $this->promo["fine"] ?><br>
        <br>
       
    </p>
    
    
    <br>
    <p>
        CODICE COUPON: <?= $this->coupon["ID_Coupon"] ?>
    </p>
    <p>
        Il seguente coupon è stato emesso da:<br>
        <img src=<?= $this->logo ?>>
    </p>

    <div class="btn_flayer" id="stampa">
        <input type="submit" value="Stampa" class="ottieni">
    </div>

  
    <div class="btn_flayer" class="due">
        <?= $this->Continua() ?>
    </div>

    <?php if ($this->doppio == "si"): ?>
        <p>
        <br><div id="doppio">Attenzione! Hai già acquisito questo coupon, potrai usufruirne una sola volta!</div>
    </p>
<?php endif; ?>
</div>    