<div id="titlePage">
    <h3>Aziende</h3>
</div>
<?php foreach ($this->aziende as $az) : ?>
    <div id="elemento">  
        <div id="tit">
            <h2> <?= $az->nome ?> </h2>
        </div>

        <!-- prende il css dalla classe .img_promo-->
        <?= $this->aziendaImg($az->logo) ?>

        <div id="desc" class="azienda">

            <?= $az->descrizione ?>

        </div>

    </div> 

<?php endforeach; ?>

<?php
if ($this->aziende instanceof Zend_Paginator) {
    echo $this->paginationControl($this->aziende, 'Sliding', 'public/paginator/_paginatorAz.phtml');
}
?>