
<?php foreach ($this->faq as $cat) : ?>
    <div id="elemento">  
        <div id="tit" class="faq">
            <h2 class="faq"> <?= $cat->domanda ?> </h2>
        </div>

        <div id="desc">

            <?= $cat->risposta ?>

        </div>

    </div> 

 <?php endforeach;?>

  <?php if($this->faq instanceof Zend_Paginator) {
	  		echo $this->paginationControl($this->faq,'Sliding','public/paginator/_paginatorFaq.phtml');
	  } 
	  ?>