<?php
$this->headScript()
        ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
        ->appendFile($this->baseUrl('js/functions.js'))
        ->captureStart()
?>

$(function()
{
    toggleFAQ();
});

<?php $this->headScript()->captureEnd() ?>


<div id="titlePage">
    <h3>Faq</h3>
</div>
<?php foreach ($this->faq as $cat) : ?>
    <div id="elemento">  
        <div id="tit" class="faq">
            <h2 class="faq"> <?= $cat->domanda ?> </h2>
        </div>
        <div id="desc">

            <?= $cat->risposta ?>

        </div>

    </div> 

 <?php endforeach;?>

  <?php if($this->faq instanceof Zend_Paginator) {
	  		echo $this->paginationControl($this->faq,'Sliding','public/paginator/_paginatorFaq.phtml');
	  } 
	  ?>