<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->appendFile($this->baseUrl('js/functions.js'))
	->captureStart() ?>

// codice jQuery inserito da view-script nella sezione head della pagina
$(function()
{
	var actionUrl='<?= $this->url(array('controller' => 'public', 'action' => 'validatelogin',), 'default'); ?>';
	var formName='<?= $this->loginForm->getName() ?>';
	$(":input").on('blur', function(event) {
        var formElementId = $(this).attr('id');
        doValidation(formElementId, actionUrl, formName);
    });
});

<?php $this->headScript()->captureEnd() ?>

<h3 id="titsign">Login</h3>
<br>

<?= $this->loginForm; ?>

<br>
<div class="login">Se non sei registrato

    <a href="<?=
    $this->url(array(
        'controller' => 'public',
        'action' => 'signin',
            ), 'default', true);
    ?>" title="Registrati">REGISTRATI</a>
</div>