<!inizio del div della promozione>

<?php foreach ($this->promozioni as $azienda) : ?>
    <div id="elemento">  
        <div id="tit">
            <h2> <?= $azienda->titolo ?> </h2>
        </div>

        <!-- prende il css dalla classe .img_promo-->
        <?= $this->promoImg($azienda->immagine) ?>

        <div id="pricebox">

            <?= $this->Price($azienda) ?>

        </div>

        <div id="desc" class="promo">

            <?= $azienda->descrizione ?>

        </div>

        <input id="submit_buy" type="submit" value="Ottieni">

    </div> 
    <!-- fine div della promozione-->
<?php endforeach; ?>


<?php
if ($this->promozioni instanceof Zend_Paginator) {
    echo $this->paginationControl($this->promozioni, 'Sliding', 'public/paginator/_paginator.phtml');
} 
	  