<!inizio del div della promozione>
<div id="titlePage">
    <h3>Promozioni</h3>
</div>
<?php foreach ($this->promozioni as $promo) : ?>
    <div id="elemento">  
        <div id="tit">
            <h2> <?= $promo->titolo ?> </h2>
        </div>

        <!-- prende il css dalla classe .img_promo-->
        <?= $this->promoImg($promo->immagine) ?>

        <div id="pricebox">

            <?= $this->Price($promo) ?>

        </div>

        <div id="desc" class="promo">

            <?= $promo->descrizione ?>

        </div>
        
        <?= $this->Ottieni($promo->ID_Promozione) ?>

    </div> 
    <!-- fine div della promozione-->
<?php endforeach; ?>


        <input id="submit_buy" type="submit" value="Ottieni">


<?php
if ($this->promozioni instanceof Zend_Paginator) {
    echo $this->paginationControl($this->promozioni, 'Sliding', 'public/paginator/_paginator.phtml');
} 
	  