<!inizio del div della promozione>
<div id="titlePage">
    <h3>Risultato Ricerca Promozioni</h3>
</div>
<?php if (count($this->trovate) == 0) : ?>
    <div id="elemento">
        <div id="tit">
            <h4> Nessun risultato trovato </h4>
        </div>
    </div>
<?php endif; ?>
<?php foreach ($this->trovate as $promo) : ?>
    <div id="elemento">
        <div id="tit">
            <h2> <?= $promo->titolo ?> </h2>
        </div>

        <!-- prende il css dalla classe .img_promo-->
        <?= $this->promoImg($promo->immagine) ?>

        <div id="pricebox">

            <?= $this->Price($promo) ?>

        </div>

        <div id="desc" class="promo">

            <p><?= $promo->descrizione ?></p>
            <p><?= '<b>Azienda: </b> &nbsp;' . $promo->ID_Azienda ?></p>
            <p><?= '<b>Categoria: </b> &nbsp;' . $promo->ID_Categoria ?></p>
            <p><?= '<b>Data Inizio: </b> &nbsp;' . $promo->inizio ?></p>
            <p><?= '<b>Data Fine: </b> &nbsp;' . $promo->fine ?></p>
            
        </div>

        <?= $this->Ottieni($promo->ID_Promozione) ?>

    </div> 
    <!-- fine div della promozione-->
<?php endforeach; ?>


<?php
if ($this->trovate instanceof Zend_Paginator) {


    echo $this->paginationControl($this->trovate, 'Sliding', 'public/paginator/_pagSearch.phtml', $this->params);
} 