<!inizio del div della promozione>
<div id="titlePage">
    <h3>Risultato Ricerca Promozioni</h3>
</div>
<?php foreach ($this->trovate as $promo) : ?>
<div id="elemento">
        <div id="tit">
            <h2> <?= $promo->titolo ?> </h2>
        </div>

        <!-- prende il css dalla classe .img_promo-->
        <?= $this->promoImg($promo->immagine) ?>

        <div id="pricebox">

            <?= $this->Price($promo) ?>

        </div>

        <div id="desc" class="promo">

            <p><?= $promo->descrizione ?></p>
            <div id="az" class="promo">

                <p><?= '<h4>Azienda: </h4>' . $promo->ID_Azienda ?></p>

            </div>
            <div id="cat" class="promo">

                <p><?= '<h4>Categoria: </h4>' . $promo->ID_Categoria ?></p>

            </div>
        </div>

         <?= $this->Ottieni($promo->ID_Promozione) ?>

    </div> 
    <!-- fine div della promozione-->
<?php endforeach; ?>


<?php
if ($this->trovate instanceof Zend_Paginator) {
   
    
    echo $this->paginationControl($this->trovate, 'Sliding', 'public/paginator/_pagSearch.phtml',$this->params);
} 