
<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->appendFile($this->baseUrl('js/functions.js'))
	->captureStart() ?>

// codice jQuery inserito da view-script nella sezione head della pagina
$(function()
{
	var actionUrl='<?= $this->url(array('controller' => 'public', 'action' => 'validatesignin',), 'default'); ?>';
	var formName='<?= $this->signinForm->getName() ?>';
	$(":input").on('blur', function(event) {
        var formElementId = $(this).attr('id');
        doValidation(formElementId, actionUrl, formName);
    });
});

<?php $this->headScript()->captureEnd() ?>

<h3>Registrati</h3>
<p>Utilizza questa form per la registrazione</p>
<br>

<?= $this->signinForm; ?>