<div class="static">
    <div id="titlePage">
        <h3>Chi Siamo</h3>
    </div>
    <p>123COUPON! nasce con l’intento di rendere più facilmente accessibili le offerte presenti sul mercato e promosse dalle aziende, basandosi sull’idea di non utilizzare l’acquisto online, ma di portare il cliente a recarsi personalmente nei punti vendita aderenti. </p>
    <p>In tal modo anche coloro che non sono esperti di e-commerce saranno in grado, con la semplice stampa di un coupon, di poter usufruire di una particolare offerta, altrimenti non disponibile localmente dai rivenditori. </p>
    <p>La registrazione al sito è molto semplice: è richiesto l’inserimento di alcune credenziali di accesso, utili all’identificazione univoca del cliente, e in pochi passi sarete già pronti per poter usufruire delle promozioni! </p>
    <p>La visualizzazione delle offerte viene effettuata in base alla categoria o all’azienda, ed è inoltre possibile effettuare ricerche in base ad una parola-chiave. Una volta scelto il coupon che fa per voi non vi resta che stamparlo!</p>
</div>