<div id="menu">
    <ul>
        <!HOME>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'index',
                                        ), 
                                        'default',true);?>" title="Home">Home	</a></p>
        </li>
        <!Aggiungi Promozione>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'staff',
                                        'action'     => 'newpromo',
                                        ), 
                                        'default',true);?>" title="AddPromo">Aggiungi Promozione	</a></p>
        </li>
        <!Elimina Promozione>
        <li>
            <p class="p_menu"><a href="" title="Chi Siamo">Elimina Promozione	</a></p>
        </li>

        <!Modifica Promozione>
        <li>
            <p class="p_menu"><a href="" title="Chi Siamo">Modifica Promozione	</a></p>
        </li>


    </ul>
</div>