<div id="menu">
    <ul>
        <!HOME>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'public',
                'action' => 'index',
                    ), 'default', true);
            ?>" title="Promozioni"><p class="p_menu">Promozioni	</p></a>
        </li>
        <!AZIENDE>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'public',
                'action' => 'aziende',
                    ), 'default', true);
            ?>" title="Aziende"><p class="p_menu">Aziende	</p></a>
        </li>
        <!CHI SIAMO>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'public',
                'action' => 'viewstatic',
                'staticPage' => 'who'), 'default', true
            );
            ?>" title="Chi Siamo"><p class="p_menu">Chi Siamo	</p></a>
        </li>
        <!DOVE SIAMO>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'public',
                'action' => 'viewstatic',
                'staticPage' => 'where'), 'default', true
            );
            ?>" title="Dove Siamo"><p class="p_menu">Dove Trovarci	</p></a>
        </li>
        <!CONTATTACI>
        <li>
            <a href="mailto:s1071182@studenti.univpm.it" title="Contatti"><p class="p_menu">Contattaci</p></a>
        </li>
        <!FAQ>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'public',
                'action' => 'faq',
                    ), 'default', true);
            ?>" title="FAQ"><p class="p_menu">FAQ		</p></a>
        </li>


        <!LOGIN>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'public',
                'action' => 'login',
                    ), 'default', true);
            ?>" title="Accedi al sito"><p class="p_menu">Login		</p>
        </li>
    </ul>
</div>