<?php echo $this->doctype() ?>
<html>
    <head>
	<?= $this->headMeta(); ?>
        <?= $this->headLink(); ?>
        <?= $this->headTitle(); ?>
    </head>
    <body>
        <div id="wrapper">      <!il div wrapper occupa l'intera pagina, ed è contenitore di tutti gli elementi
                                ha una larghezza minima fissata a 920px;>	
            <div id="header">   <!l'header contiene i div del logo e della barra di ricerca>
                <div id="logo"> <!contiene il link all'immagine>
			<a href="<?= $this->url(array(          //questo riferimento permmette facendo click sull'immagine
                                'controller' => 'public',       //di ricaricare la pagina inziale, avviando il la indexAction
                                'action'     => 'index',        //del PublicController
                                ), 
                                'default',true);?>"> 
                            <img id="img_logo" src=<?= $this->logo ?>><!riferimento alla posizione dell'immagine (da sistemare)>
                        </a>
		</div>
                      
		<div id="div_src" ><!questo div contiene la form di inserimento e i bottoni di login e registrazione>
				
                    <form class="src" id="form_src" name="search" action="" method="post">
						
                        <select id="cat_src" name="cat"> 
                            <option id="opt_src">Tutte le categorie</option>
                            <option id="opt_src">cat1</option>
                            <option id="opt_src">cat2</option>
                        </select>		

                        <input id="desc_src" name="desc" type="text" placeholder="Cerca"> 

                        <input id="submit_src" type="submit" value="Cerca">
									
                    </form>
							
                    <div id="login" class="src">
									
                        <input class="submit" type="submit" value="Accedi">
                        <input class="submit" type="submit" value="Registrati">
						
                    </div>
		</div>
            </div>
            
            <div id="main_page">
		<div id="menu">
                    <?= $this->render('_menu.phtml') ?>
		</div>
		<div id="page"> <!Qi viene caricato dinamicamente il contenuto della pagina
                                in base alla nostra selezione sul menu, il public controller
                                comporrà la vista e la farà stampare
                                al primo avvio, o ad un eventuale ricaricamento della pagina home
                                troveremo il contenuto del file index.phtml>
                    
                    <?php echo $this->layout()->content; ?>
                    
                    <div class="clear"> </div>
		</div>
		<!-- End Right Column -->
                <div id="footer"> This is the Footer </div>
		  <!-- End Footer -->
            </div>
        </div>    
    </body>
</html>
