<div id="menu">
    <ul>
        <!HOME>
        <li>
            <a href="<?=
                $this->url(array(
                    'controller' => 'public',
                    'action' => 'promo',
                    'logged' => 'staff'
                        ), 'default', true);
                ?>" title="Home"><p class="p_menu">Home	</p></a>
        </li>
        <!Aggiungi Promozione>
        <li>
            <a href="<?=
                $this->url(array(
                    'controller' => 'staff',
                    'action' => 'newpromo',
                        ), 'default', true);
                ?>" title="Aggiungi una nuova Promozione"><p class="p_menu">Aggiungi Promozione	</p></a>
        </li>
        <!Modifica Promozione>
        <li>
            <a href="<?=
                $this->url(array(
                    'controller' => 'staff',
                    'action' => 'modpromo',
                        ), 'default', true);
                ?>" title="Modifica una Promozione"><p class="p_menu">Modifica Promozione	</p></a>

        </li>

        <!PROFILO>
        <li>
            <a href="<?=
                                 $this->url(array(
                                     'controller' => 'staff',
                                     'action' => 'retrieve',
                                         ), 'default', true);
                                 ?>" title="Modifica il tuo Profilo"><p class="p_menu">Il tuo Profilo		</p></a>
        </li>

    </ul>
</div>