<div id="menu">
    <ul>
        <!HOME>
        <li>
            <p class="p_menu"><a href="<?=
                $this->url(array(
                    'controller' => 'public',
                    'action' => 'promo',
                    'logged' => 'staff'
                        ), 'default', true);
                ?>" title="Home">Home	</a></p>
        </li>
        <!Aggiungi Promozione>
        <li>
            <p class="p_menu"><a href="<?=
                $this->url(array(
                    'controller' => 'staff',
                    'action' => 'newpromo',
                        ), 'default', true);
                ?>" title="Aggiungi una nuova Promozione">Aggiungi Promozione	</a></p>
        </li>
        <!Modifica Promozione>
        <li>
            <p class="p_menu"><a href="<?=
                $this->url(array(
                    'controller' => 'staff',
                    'action' => 'modpromo',
                        ), 'default', true);
                ?>" title="Modifica una Promozione">Modifica Promozione	</a></p>

        </li>

        <!PROFILO>
        <li>
            <p class="p_menu"><a href="<?=
                                 $this->url(array(
                                     'controller' => 'staff',
                                     'action' => 'retrieve',
                                         ), 'default', true);
                                 ?>" title="Modifica il tuo Profilo">Il tuo Profilo		</a></p>
        </li>

    </ul>
</div>