<div id="header">   <!l'header contiene i div del logo e della barra di ricerca>
    <div id="logo"> <!contiene il link all'immagine>
        <a href="<?= $this->url(array(          //questo riferimento permmette facendo click sull'immagine
            'controller' => 'public',       //di ricaricare la pagina inziale, avviando il la indexAction
            'action'     => 'index',        //del PublicController
            ), 
            'default',true);?>"> 
            <img id="img_logo" src=<?= $this->logo ?>><!riferimento alla posizione dell'immagine (da sistemare)>
        </a>
	
    </div>
                      
    <div id="div_src" ><!questo div contiene la form di inserimento e i bottoni di login e registrazione>
	
        <?= $this->searchForm ?>
        
        </form>
    </div>
</div>