<div id="menu">
    <ul>
        <!INDIETRO>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'admin',
                'action' => 'index',
                    ), 'default', true);
            ?>" title="Torna alla home di area riservata"><p class="p_menu">Indietro	</p></a>
        </li>
        <!Aggiungi FAQ>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'admin',
                'action' => 'newfaq',
                    ), 'default', true);
            ?>" title="Aggiungi una nuova FAQ"><p class="p_menu">Aggiungi FAQ	</p></a>
        </li>
        <!Modifica FAQ>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'admin',
                'action' => 'modfaq',
                    ), 'default', true);
            ?>" title="Modifica una FAQ"><p class="p_menu">Modifica FAQ	</p></a>
        </li>


    </ul>
</div>