<div class="static">
    <h3>Modifica Aziende</h3>
    <p>Ecco le Aziende che puoi modificare</p>
    <br>
    <table id="modTable">
        <thead id="headmod">
            <tr>
                <th>Nome</th>
                <th>Ragione Sociale</th>
                <th>Città</th>
                <th>Indirizzo</th>
                <th>Descrizione</th>
                <th>Logo</th>
                <th>Utente</th>
                <th>Modifica</th>
                <th>Elimina</th>
            </tr>
        </thead>
        <tbody id="bodymod">
            <?php foreach ($this->righe as $utente) : ?>

                <tr>
                    <td><?= $utente["nome"] ?></td>
                    <td><?= $utente["ragione_sociale"] ?></td>
                    <td><?= $utente["citta"] ?></td>
                    <td><?= $utente["indirizzo"] ?></td>
                    <td><?= $utente["descrizione"] ?></td>
                    <td><?= $utente["logo"] ?></td>
                    <td><?= $this->utente[$utente["ID_Azienda"]] ?></td>
                    <td><a href="<?=
                        $this->url(array(
                            'controller' => 'admin',
                            'action' => 'popolateaz',
                            'ID' => $utente["ID_Azienda"]
                                ), 'default', true);
                        ?>" title="Modifica"><img class="img_mod" src=<?= $this->modifica ?>></a></td>
                    <td><a href="<?=
                        $this->url(array(
                            'controller' => 'admin',
                            'action' => 'deleteaz',
                            'ID' => $utente["ID_Azienda"]
                                ), 'default', true);
                        ?>" title="Elimina"><img class="img_mod" src=<?= $this->elimina ?>></a></td>
                </tr>

<?php endforeach; ?>
        </tbody>
    </table>

</div>