<?php
$this->headScript()
        ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
        ->appendFile($this->baseUrl('js/functions.js'))
        ->captureStart()
?>

$(function()
{
    striper();
});

<?php $this->headScript()->captureEnd() ?>

<div class="static">
    <h3>Modifica Categorie</h3>
    <p>Ecco le Categorie che puoi modificare</p>
    <br>
    <table id="modTable">
        <thead id="headmod">
            <tr>
                <th>Nome</th>
                <th>Modifica</th>
                <th>Elimina</th>
            </tr>
        </thead>
        <tbody id="bodymod">
            <?php foreach ($this->righe as $cat) : ?>

                <tr>
                    <td><?= $cat["nome"] ?></td>
                    <td><a href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'popolatecat',
                                        'ID' => $cat["ID_Categoria"]
                                        ), 
                                        'default',true);?>" title="Modifica"><img class="img_mod" src=<?= $this->modifica?>></a></td>
                    <td><a href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'deletecat',
                                        'ID' => $cat["ID_Categoria"]
                                        ), 
                                        'default',true);?>" title="Elimina"><img class="img_mod" src=<?= $this->elimina?>></a></td>
                </tr>
                
            <?php endforeach; ?>
        </tbody>
    </table>

</div>