<div class="static">
    <h3>Modifica Utenti</h3>
    <p>Ecco gli utenti che puoi modificare</p>
    <br>
    <table id="modTable">
        <thead id="headmod">
            <tr>
                <th>Username</th>
                <th>Nome</th>
                <th>Cognome</th>
                <th>Genere</th>
                <th>Data Di Nascita</th>
                <th>Telefono</th>
                <th>Indirizzo</th>
                <th>Email</th>
                <th>Ruolo</th>
                <th>Modifica</th>
                <th>Elimina</th>
            </tr>
        </thead>
        <tbody id="bodymod">
            <?php foreach ($this->righe as $promozione) : ?>

                <tr>
                    <td><?= $promozione["Username"] ?></td>
                    <td><?= $promozione["nome"]?></td>
                    <td><?= $promozione["cognome"]?></td>
                    <td><?= $promozione["genere"] ?></td>
                    <td><?= $promozione["eta"] ?></td>
                    <td><?= $promozione["telefono"] ?></td>
                    <td><?= $promozione["indirizzo"] ?></td>
                    <td><?= $promozione["email"] ?></td>
                    <td><?= $promozione["role"] ?></td>
                    <td><a href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'popolateusr',
                                        'ID' => $promozione["ID_Utente"]
                                        ), 
                                        'default',true);?>" title="Modifica"><img class="img_mod" src=<?= $this->modifica?>></a></td>
                    <td><a href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'deleteusr',
                                        'ID' => $promozione["ID_Utente"]
                                        ), 
                                        'default',true);?>" title="Elimina"><img class="img_mod" src=<?= $this->elimina?>></a></td>
                </tr>
                
            <?php endforeach; ?>
        </tbody>
    </table>

</div>