<div class="static">
    <h3>Modifica Utenti</h3>
    <p>Ecco li utenti che puoi modificare</p>
    <br>
    <table id="modTable">
        <thead id="headmod">
            <tr>
                <th>Username</th>
                <th>Nome</th>
                <th>Cognome</th>
                <th>Genere</th>
                <th>Data Di Nascita</th>
                <th>Telefono</th>
                <th>Indirizzo</th>
                <th>Email</th>
                <th>Ruolo</th>
                <th>Modifica</th>
                <th>Elimina</th>
            </tr>
        </thead>
        <tbody id="bodymod">
            <?php foreach ($this->righe as $utente) : ?>
                 <?php if($utente["Username"] != $this->utente) : ?>
                <tr>
                    <td><?= $utente["Username"] ?></td>
                    <td><?= $utente["nome"]?></td>
                    <td><?= $utente["cognome"]?></td>
                    <td><?= $utente["genere"] ?></td>
                    <td><?= $utente["eta"] ?></td>
                    <td><?= $utente["telefono"] ?></td>
                    <td><?= $utente["indirizzo"] ?></td>
                    <td><?= $utente["email"] ?></td>
                    <td><?= $utente["role"] ?></td>
                    <td><a href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'popolateusr',
                                        'ID' => $utente["ID_Utente"]
                                        ), 
                                        'default',true);?>" title="Modifica"><img class="img_mod" src=<?= $this->modifica?>></a></td>
                    <td><a href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'deleteusr',
                                        'ID' => $utente["ID_Utente"]
                                        ), 
                                        'default',true);?>" title="Elimina"><img class="img_mod" src=<?= $this->elimina?>></a></td>
                </tr>
                <?php endif;?>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>