<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->appendFile($this->baseUrl('js/functions.js'))
	->captureStart() ?>

$(function()
{
	var actionUrl='<?= $this->url(array('controller' => 'admin', 'action' => 'validatecat',), 'default'); ?>';
	var formName='<?= $this->newcatform->getName() ?>';
	$(":input").on('blur', function(event) {
        var formElementId = $(this).attr('id');
        doValidation(formElementId, actionUrl, formName);
    });
});

<?php $this->headScript()->captureEnd() ?>
<div class="static">
 <h3>Aggiungi Categoria</h3>
 <p>Utilizza questa form per inserire una nuova Categoria</p>
  <?php echo $this->newcatform ?>
</div>