<div class="static">
    <h3>Statistiche</h3>
    <br>
    <p>Numero coupon emessi in totale fin ora: <?= $this->nCoupon ?></p>
    <br>
    <div>
        <div class="statsSelector">
            <h4><a href="<?=
                $this->url(
                        array(
                    'controller' => 'admin',
                    'action' => 'stats',
                    'param' => 'p'), 'default', true);
                ?>">Coupon Emessi per Promozione</a></h4>
        </div>
        <div class="statsSelector">
            <h4><a href="<?=$this->url(
                        array(
                    'controller' => 'admin',
                    'action' => 'stats',
                    'param' => 'u'), 'default', true);
                ?>">Coupon Emessi per Utente</a></h4>
        </div>

    </div>

    <div id="stat">
        <?php if ($this->by == 'p') : ?>  
            <table id="modTable">
                <thead id="headmod">
                    <tr>
                        <th>Promozione</th>
                        <th>Coupon Emessi</th>
                    </tr>
                </thead>

                <tbody id="bodymod">
                    <?php foreach ($this->p as $prom) : ?>

                        <tr>
                            <td><?= $prom["Promozione"] ?></td>
                            <td><?= $prom["couponEmessi"] ?></td>
                        </tr>               
                    <?php endforeach; ?>
                </tbody>        
            </table>

        <?php else : if ($this->by == 'u') : ?>  

                <table id="modTable">
                    <thead id="headmod">
                        <tr>
                            <th>Username</th>
                            <th>Coupon Acquistati</th>

                        </tr>
                    </thead>

                    <tbody id="bodymod">
                        <?php foreach ($this->u as $azienda) : ?>
                            <tr>
                                <td><?= $azienda["Username"] ?></td>
                                <td><?= $azienda["couponAcquistati"] ?></td>
                            </tr>               
                        <?php endforeach; ?>
                    </tbody>        
                </table>
            <?php endif; ?>
        <?php endif; ?>
        <br><br>
    </div>
</div>