<?php if ($this->pageCount > 1): ?>
    <div id="pagination">
        <?php echo $this->firstItemNumber; ?> - <?= $this->lastItemNumber; ?> di <?= $this->totalItemCount; ?> ---

        <!-- Link alla prima pagina -->
        <?php if (isset($this->previous)): ?>
          <a href="<?= $this->url(array('controller' => 'public', 'action' => 'find', 'page' => $this->first, 'ID_Categoria' => $this->ID_Categoria, 'words'=>$this->words)); ?>">Inizio</a> |
        
        <!-- Link alla pagina precedente -->
          <a href="<?= $this->url(array('controller' => 'public', 'action' => 'find', 'page' => $this->previous, 'ID_Categoria' => $this->ID_Categoria, 'words'=>$this->words)); ?>">&lt; Precedente</a> |
        
        <?php else: ?>
           Inizio |  &lt; Precedente |
        <?php endif; ?>

        <!-- Link alla pagina successiva -->
        <?php if (isset($this->next)): ?>
          <a href="<?= $this->url(array('controller' => 'public', 'action' => 'find', 'page' => $this->next, 'ID_Categoria' => $this->ID_Categoria, 'words'=>$this->words)); ?>">Successivo &gt;</a> |

        <!-- Link all'ultima pagina -->
       
          <a href="<?= $this->url(array('controller' => 'public', 'action' => 'find', 'page' => $this->last, 'ID_Categoria' => $this->ID_Categoria, 'words'=>$this->words)); ?>">Fine</a>
        <?php else: ?>
          Successivo &gt; | Fine
        <?php endif; ?>
    </div>
<?php endif; ?>