<div id="menu">
    <ul>
        <!HOME>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'public',
                'action' => 'promo',
                    ), 'default', true);
            ?>" title="Promozioni"><p class="p_menu">Promozioni	</p></a>
        </li>

        <!AZIENDE>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'public',
                'action' => 'aziende',
                    ), 'default', true);
            ?>" title="Aziende"><p class="p_menu">Aziende	</p></a>
        </li>

        <!CHI SIAMO>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'public',
                'action' => 'viewstatic',
                'staticPage' => 'who',
                    ), 'default', true
            );
            ?>" title="Chi Siamo"><p class="p_menu">Chi Siamo	</p></a>
        </li>

        <!DOVE SIAMO>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'public',
                'action' => 'viewstatic',
                'staticPage' => 'where',
                    ), 'default', true
            );
            ?>" title="Dove Siamo"><p class="p_menu">Dove Trovarci	</p></a>
        </li>

        <!CONTATTACI>
        <li>
            <a href="mailto:s1071182@studenti.univpm.it" title="Contatti"><p class="p_menu">Contattaci</p></a>
        </li>

        <!FAQ>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'public',
                'action' => 'faq',
                    ), 'default', true);
            ?>" title="FAQ"><p class="p_menu">FAQ		</p></a>
        </li>   



        <!AREA RISERVATA>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'admin',
                'action' => 'index',
                    ), 'default', true);
            ?>" title="Accedi all'area riservata"><p class="p_menu">Area Riservata		</p></a>
        </li>

        <!LOGOUT>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'admin',
                'action' => 'logout',
                    ), 'default', true);
            ?>" title="Fai il logout"><p class="p_menu">Logout		</p></a>
        </li>
        <!RELAZIONE>
        <li>
            <a href="<?= $this->linkRelazione ?>" target="_BLANK" title="Visualizza la Relazione"><p class="p_menu">Relazione		</p></a>
        </li>
    </ul>
</div>