<div id="menu">
    <ul>
        <!HOME>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'public',
                'action' => 'promo',
                'logged' => 'admin'
                    ), 'default', true);
            ?>" title="Home"><p class="p_menu">Home	</p></a>
        </li>
        <!CRUD AZIENDE>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'admin',
                'action' => 'aziende',
                    ), 'default', true);
            ?>" title="Gestisci Aziende"><p class="p_menu">Gestisci Aziende</p></a>
        </li>
        <!CRUD CATEGORIE>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'admin',
                'action' => 'categorie',
                    ), 'default', true);
            ?>" title="Gestisci Categorie"><p class="p_menu">Gestisci Categorie	</p></a>
        </li>

        <!CRUD UTENTI>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'admin',
                'action' => 'utenti',
                    ), 'default', true);
            ?>" title="Gestisci Utenti"><p class="p_menu">Gestisci Utenti	</p></a>
        </li>

        <!CRUD FAQ>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'admin',
                'action' => 'faq',
                    ), 'default', true);
            ?>" title="Gestisci Faq"><p class="p_menu">Gestisci FAQ	</p></a>
        </li>

        <!STATISTICHE>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'admin',
                'action' => 'stats',
                    ), 'default', true);
            ?>" title="Accedi alle Statistiche"><p class="p_menu">Statistiche	</p></a>
        </li>
        <!LOGOUT>
        <li>
            <a href="<?=
            $this->url(array(
                'controller' => 'admin',
                'action' => 'logout',
                    ), 'default', true);
            ?>" title="Fai il logout"><p class="p_menu">Logout		</p></a>
        </li>

    </ul>
</div>